void program1();
void program2();
void program3();
void program4();
void program5();
void program6();
void program7();
void program8();
void program9();
void program10();
void program11();
void program12();
void program13();
void program14();
void program15();
void program16();
void program17();
void program18();
void program19();
void program20();
void program21();
void program22();
void program23();
void program24();
void program25();
void program26();
void program27();
void program28();
void program29();
void program30();
void program31();
void program32();
void program33();
void program34();
void program35();
void program36();
void program37();
void program38();
void program39();
int check();

#ifndef LANGUAGESANDMETHODS_SEMESTR1_H
#define LANGUAGESANDMETHODS_SEMESTR1_H

#endif //LANGUAGESANDMETHODS_SEMESTR1_H
